### ISSUE TITLE
Settings cant be found

### ISSUE THREAD

**Issue by iwontknow** [iOSonntag/vscode-flutter-easylocalization#2]
I might beeing totally slow right now, but i dont find the settings for this extension?
Where do i set them?

**Comment by zhoudajun-ola** [comment]
modify config in: .vscode/settings.json
```
  "fluttereasylocalization.translationDir": "assets/lang",
  "fluttereasylocalization.generatedKeyFileName": "lang_keys.g.dart",
  "fluttereasylocalization.generalTranslationPrefix": ""
```

then it work.

**Comment by iwontknow** [comment]
Thank you! Works like charm.

**Comment by iOSonntag** [comment]
@iwontknow I just added the settings section in the vscode sttings window, update is on the way.
